#!/bin/bash
#==========================================#
#                 poshd                    #
#  https://github.com/ponyofshadows/poshd  #
#==========================================#
set -e

# ----------------
## Strategies for parsing parameters
# 
# - Adjacent non-option parameters will be concatenated into one object
# |__ objects starting with "-e" or without preceding options -> event
# |__ objects starting with "-p" -> project
# |__ objects starting with "-f" -> file
# |__ objects starting with "-d" -> disk
# |__ objects starting with "-l" -> keyword
# - objects call specfic functions
# |__ event -> update_event()
# |__ project -> update_project()
# |__ disk -> update_disk()
# |__ event & project -> link()
#
# - some options call specfic functions
# |__ "-init" --> init()
# |__ "-l" --> list()
# |__ "-b" --> backup()
# |__ "-r" --> recover()
# |__ "-rm" --> rm_event()
# ----------------
