#!/bin/bash
#==========================================#
#                 poshd                    #
#  https://github.com/ponyofshadows/poshd  #
#==========================================#
set -e
PO_PATH="$HOME/tmp/test/all"

source lib/functions.sh

# ----------------
## Strategies for parsing parameters
# 
# - Adjacent non-option parameters will be concatenated into one object
# |__ objects starting with "-e" or without preceding options -> (event, title, path, date)
# |__ objects starting with "-p" -> (project, title, path, status)
# |__ objects starting with "-f" -> (file, path)
# |__ objects starting with "-d" -> (disk, name, status)
# |__ objects starting with "-l" -> (keyword, content, date_from, date_to)
# - objects call specfic functions
# |__ event -> update_event
# |__ project -> update_project
# |__ disk -> update_disk
# |__ event & project -> link
#
# - some options call specfic functions
# |__ "-init" --> po_init
# |__ "-l" --> list
# |__ "-b" --> backup
# |__ "-r" --> recover
# |__ "-rm" --> rm_event (always remove frist object)
# |__ "--debug" --> debug
# ----------------
CURRENT_CONTENT=""
current_object=("event")
object_list=()
declare -A option_actions

if [[ "$#" == 0 ]]; then
  # equivalent to option "po -l"
  echo "list"
else
  for arg in "$@"
  do
    if [[ ! "$arg" == -* ]]; then
      # 2. If current arg is not a option
      echo "content"
    else  
      # 1. If current arg is a option
      # |__ 1) complete last object
      if [[ -n "$CURRENT_CONTENT" ]]; then
        if [[ "${current_object[0]}" == "event" || "${current_object[0]}" == "project" ]]; then
          # title
          current_object[1]="${CURRENT_CONTENT%%/*}"
          # path
          current_object[2]="${CURRENT_CONTENT#*/}"
        else
          current_object[1]="$CURRENT_CONTENT"
        fi
        CURRENT_CONTENT=""
        object_list+=("${current_object}")
        current_object=("event")
      fi
      # |__ 2) Specific operations
      case $arg in
        -e*)
          current_object[0]="event"
          current_object[3]="${arg#*-e}"
          current_object[3]="${current_object[4]#*:}"
          current_object[3]=$(po_date "${current_object[4]}")
          ;;
        -p*)
          current_object[0]="project"
          current_object[3]="${arg#*-p}"
          current_object[3]="${current_object[4]#*:}"
          ;;
        -f*)
          current_object[0]="file"
          ;;
        -d*)
          current_object[0]="disk"
          current_object[2]="${arg#*-d}"
          current_object[2]="${current_object[3]#*:}"
          ;;
        -l*)
          current_object[0]="keywords"
          current_object[2]="${arg#*-l}"
          current_object[2]="${current_object[3]#*:}"
          PERIOD=$(po_period "${current_object[3]}")
          current_object[2]="${PERIOD%%,*}"
          current_object[3]="${PERIOD#*,}"
          ;;
        -rm*)
          option_actions["remove"]="$arg"
          ;;
        -b)
          option_actions["backup"]="$arg"
          ;;
        -r)
          option_actions["recover"]="$arg"
          ;;
        -init)
          po_init
          ;;
        --debug)
          option_actions["debug"]="$arg"
          ;;
      esac
    fi
  done
fi
